<?php

namespace Aitam\CaffeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentiCaffeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentiCaffeRepository extends EntityRepository
{
}
