<?php

namespace Aitam\OpportunitaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OpportunitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportunitaRepository extends EntityRepository
{
	
	public function getLatestOpportunita($limit = null)
	{
		$qb = $this->createQueryBuilder('o')
		->select('o')
		->leftJoin('o.commentiopportunita', 'c')
		->addOrderBy('o.created', 'DESC');
	
		if (false === is_null($limit))
			$qb->setMaxResults($limit);
	
		return $qb->getQuery()
		->getResult();
	}
	
	public function getBlogOpportunita($limit = null)
	{
		$qb = $this->createQueryBuilder('o')
		->select('o')
		->leftJoin('o.commentiopportunita', 'c')
		->addOrderBy('o.created', 'DESC');
	
		if (false === is_null($limit))
			$qb->setMaxResults($limit);
	
		return $qb->getQuery()
		->getResult();
	}
		
}