imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @AitamIndexBundle/Resources/config/config.yml }
    - { resource: @AitamIndexBundle/Resources/config/services.yml }
    - { resource: @AitamAgendaBundle/Resources/config/services.yml }
    - { resource: @AitamAgendaBundle/Resources/config/config.yml }
    - { resource: @AitamRaccontiBundle/Resources/config/service.yml }

framework:
    secret:          "%secret%"
    translator: ~
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~
 
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
 
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    SonataUserBundle: ~
                    ApplicationSonataUserBundle: ~
                    AitamIndexBundle: ~
                    AitamAgendaBundle: ~
                    AitamDavisitareBundle: ~
                    AitamOpportunitaBundle: ~
                    AitamRaccontiBundle: ~
                    
stof_doctrine_extensions:
    default_locale: en_US

    orm:
        default: 
          timestampable : true                    
 
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    registration:
        confirmation:
            enabled:    true
            from_email:
                address:        registration@acmedemo.com
                sender_name:    Nome Sito
    resetting:
        email:
            from_email:
                address:        resetting@acmedemo.com
                sender_name:    %sitename% - Password dimenticata?
    user_class:     Application\Sonata\UserBundle\Entity\User
 
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
    profile:  # Authentication Form
        form:
            type:               fos_user_profile
            name:               fos_user_profile_form
            validation_groups:  [Authentication] # Please note : this is not the default value
 
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
 
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
 
sonata_admin:
    title:      Sonata Project
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
 
        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
 
sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~
 
    templates:
        form:
            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
        filter:
            - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
        types:
            list:
                array:      SonataAdminBundle:CRUD:list_array.html.twig
                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
                date:       SonataAdminBundle:CRUD:list_date.html.twig
                time:       SonataAdminBundle:CRUD:list_time.html.twig
                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_list_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig
 
            show:
                array:      SonataAdminBundle:CRUD:show_array.html.twig
                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
                date:       SonataAdminBundle:CRUD:show_date.html.twig
                time:       SonataAdminBundle:CRUD:show_time.html.twig
                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig
 
sonata_user:
    security_acl:           false
    impersonating_route:    AitamIndexBundle_homepage # or any route you want to use
    class:                  # Entity Classes
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group
 
    admin:                  # Admin Classes
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
 
        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
 
    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]
          
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar    

services:

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    aitam.index.admin.dinuovo:
      class: Aitam\IndexBundle\Admin\DinuovoAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: aitam_index, label: dinuovo }
      arguments: [null, Aitam\IndexBundle\Entity\Dinuovo, AitamIndexBundle:DinuovoAdmin]
      calls:
          - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ] 
      
    aitam.index.admin.commenti:
      class: Aitam\IndexBundle\Admin\CommentiAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: aitam_index, label: commenti }
      arguments: [null, Aitam\IndexBundle\Entity\Commenti, AitamIndexBundle:CommentiAdmin]
  
    aitam.agenda.admin.agenda:
      class: Aitam\AgendaBundle\Admin\AgendaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, audit : false , group: enrico_blog, label: mynews }
      arguments: [null, Aitam\AgendaBundle\Entity\Mynews, AitamAgendaBundle:AgendaAdmin]
      calls:
          - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ] 
          
    aitam.davisitare.admin.davisitare:
      class: Aitam\DavisitareBundle\Admin\DavisitareAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: aitam_davisitare, label: davisitare }
      arguments: [null, Aitam\DavisitareBundle\Entity\Davisitare, AitamDavisitareBundle:DavisitareAdmin]
      calls:
          - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ] 
      
    aitam.davisitare.admin.commentidavisitare:
      class: Aitam\DavisitareBundle\Admin\CommentiDavisitareAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: aitam_davisitare, label: commentidavisitare }
      arguments: [null, Aitam\DavisitareBundle\Entity\Commentidavisitare, AitamDavisitareBundle:CommentidavisitareAdmin]
      
    aitam.Opportunita.admin.Opportunita:
      class: Aitam\OpportunitaBundle\Admin\OpportunitaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: aitam_Opportunita, label: Opportunita }
      arguments: [null, Aitam\OpportunitaBundle\Entity\Opportunita, AitamOpportunitaBundle:OpportunitaAdmin]
      calls:
          - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ] 
      
    aitam.Opportunita.admin.commentiOpportunita:
      class: Aitam\OpportunitaBundle\Admin\CommentiOpportunitaAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: aitam_Opportunita, label: commentiOpportunita }
      arguments: [null, Aitam\OpportunitaBundle\Entity\CommentiOpportunita, AitamOpportunitaBundle:CommentiOpportunitaAdmin]
     
    aitam.Racconti.admin.Racconti:
      class: Aitam\RaccontiBundle\Admin\RaccontiAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: aitam_Racconti, label: Racconti }
      arguments: [null, Aitam\RaccontiBundle\Entity\Racconti, AitamRaccontiBundle:RaccontiAdmin]
      calls:
          - [ setLabelTranslatorStrategy, [ @sonata.admin.label.strategy.underscore ] ]
  #simple_things_entity_audit:
  #  audited_entities:
  #      - Aitam/IndexBundle\Entity\Dinuovo
  #      - Aitam/IndexBundle\Entity\Commenti
  #      - Aitam/AgendaBundle\Entity\Mynews
  #      - Aitam/IndexBundle\Entity\Davisitare
  #      - Aitam/IndexBundle\Entity\Commentidavisitare