parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     itam
    database_user:     enrico 
    database_password: tempe08

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            ita
    secret:            ThisTokenIsNotSoSecretChangeIt
    sitename:          itam