parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     itam2
    database_user:     enrico 
    database_password: tempe08

    mailer_transport:  smtp
    mailer_user:       enricotempesti
    mailer_password:   tempes08
    mailer_encryption: ssl://smtp.gmail.com
    mailer_auth_mode:  login
    mailer_host:       smtp.gmail.com
    mailer_port:       465

    locale:            ita
    secret:            ThisTokenIsNotSoSecretChangeIt
    sitename:          itam2