AitamIndexBundle_homepage:
    pattern:  /index
    defaults: { _controller: AitamIndexBundle:Page:index }
    requirements:
        _method:  GET

AitamIndexBundle_contact:
    pattern:  /contact
    defaults: { _controller: AitamIndexBundle:Page:contact }
    requirements:
        _method:  GET|POST
        
AitamIndexBundle_about:
    pattern:  /about
    defaults: { _controller: AitamIndexBundle:Page:about }
    requirements:
        _method:  GET 
        
AitamIndexBundle_statuto:
    pattern:  /statuto
    defaults: { _controller: AitamIndexBundle:Page:statuto }
    requirements:
        _method:  GET  
        
AitamIndexBundle_listaiscritti:
    pattern:  /listaiscritti/{page}
    defaults: { _controller: ApplicationSonataUserBundle:User:listaiscritti,page: 1  }
    requirements:
        _method:  GET 
        
AitamIndexBundle_dinuovo_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: AitamIndexBundle:Dinuovo:dinuovo }
    requirements:
        _method:  GET
        id: \d+

AitamIndexBundle_home_dinuovo:
    pattern:  /home_dinuovo/{page}
    defaults: { _controller: AitamIndexBundle:Dinuovo:home_dinuovo,page: 1 }
    requirements:
        _method:  GET 
        
AitamIndexBundle_comment_create:
    pattern:  /commenti/{dinuovo_id}
    defaults: { _controller: AitamIndexBundle:Commenti:create }
    requirements:
        _method:  POST
        blog_id: \d+ 

AitamIndexBundle_testimonial:
    pattern:  /testimonial
    defaults: { _controller: AitamRaccontiBundle:Racconti:new }
    requirements:
        _method:  GET  

AitamIndexBundle_forum_no_registrato:
    pattern:  /forum_no_registrato
    defaults: { _controller: AitamIndexBundle:Page:forum_no_registrato }
    requirements:
        _method:  GET 
        
AitamIndexBundle_caffe:
    pattern:  /caffe
    defaults: { _controller: AitamCaffeBundle:Caffe:new }
    requirements:
        _method:  GET 