parameters:
#    aitam_index.example.class: Aitam\IndexBundle\Example

services:
    enrico_blog.twig.extension:
        class: Aitam\IndexBundle\Twig\Extensions\EnricoBlogExtension
        tags:
            - { name: twig.extension }
