 
        
AitamDavisitareBundle_davisitare_show:
    pattern:  /davisitare/{id}/{slug}
    defaults: { _controller: AitamDavisitareBundle:Davisitare:Davisitare }
    requirements:
        _method:  GET
        id: \d+

AitamDavisitareBundle_home_davisitare:
    pattern:  /home_davisitare/{page}
    defaults: { _controller: AitamDavisitareBundle:Davisitare:home_davisitare,page: 1 }
    requirements:
        _method:  GET 
        
AitamDavisitareBundle_comment_create:
    pattern:  /commentidavisitare/{davisitare_id}
    defaults: { _controller: AitamDavisitareBundle:Commentidavisitare:create }
    requirements:
        _method:  POST
        blog_id: \d+ 
           