<?php

namespace Aitam\RaccontiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RaccontiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaccontiRepository extends EntityRepository {


    public function getphotoracconti($limit = null) {

        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT r.id,r.titolo,r.descrizionebreve,r.autore,r.tipo,r.created,fo.path, MIN( fo.id)  
				FROM AitamIndexBundle:Raccontiphoto fo LEFT JOIN fo.racconti r WHERE r.is_active = 1 GROUP BY r.id ')
                ->setMaxResults(20);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
