<?php

namespace Aitam\RaccontiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RaccontiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaccontiRepository extends EntityRepository
{
}
